Completed prep-css-flexbox exercise Morris Wang
wang-morris/prep-0422-code-solutions pull request #9
Opened 2022-04-22 23:31 UTC by wang-morris

https://user-images.githubusercontent.com/103090771/164817112-bd0e030f-a887-4ebf-a7e3-f2f5311e32f2.mp4

2022-04-23 16:31 UTC, thebearingedge requested changes

2022-04-23 16:31 UTC, thebearingedge commented on prep-css-flexbox/align-items.html
> +      min-height: 100vh;
Hi Morris, for all of your files here, be sure to put `flex-basis` on the `.card-wrapper`. 

`flex-basis` is meant to be used on the children of elements with `display: flex`

2022-04-24 17:42 UTC, wang-morris commented
<img width="847" alt="prep-css-flexbox-align-items" src="https://user-images.githubusercontent.com/103090771/164989340-6cf22993-a247-4265-9464-6eb3d2c460f8.png">

2022-04-25 16:09 UTC, thebearingedge approved these changes

2022-04-25 21:55 UTC, merged